name: Build and deploy Node.js app to Azure Web Apps without ZIP

on:
  pull_request:
    branches:
      - main
    types: 
      - closed
  workflow_dispatch:

permissions:
  id-token: write  # Add this to allow OIDC-based authentication
  contents: read   # Add read permissions for contents

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: React/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('React/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build
        working-directory: React/frontend

      # List out the build folder to check if static files are present
      - name: Check static folder contents in build directory
        run: |
          echo "Checking if static files are present after build:"
          ls -la React/frontend/build/static
          ls -la React/frontend/build/static/css
          ls -la React/frontend/build/static/js
          ls -la React/frontend/build/static/media
        continue-on-error: true

      # Add correct Azure login step with OIDC-based authentication
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          enable-AzPSSession: false

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myvdtreact'
          slot-name: 'Production'
          package: React/frontend/build
          clean: true
