name: Build and deploy Node.js and Python apps to Azure Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-pr-comments:
    runs-on: ubuntu-latest
    outputs:
      deploy_frontend: ${{ steps.set_output.outputs.deploy_frontend }}
      deploy_backend: ${{ steps.set_output.outputs.deploy_backend }}
    steps:
      - name: Check PR comments for frontend or backend triggers
        id: check_comments
        run: |
          echo "Checking for 'frontend::' or 'backend::' in PR comments..."
          COMMENTS=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
          echo "PR Comments: $COMMENTS"
          
          if [[ "$COMMENTS" == *"frontend::"* ]]; then
            echo "frontend=true" >> $GITHUB_ENV
          else
            echo "frontend=false" >> $GITHUB_ENV
          fi

          if [[ "$COMMENTS" == *"backend::"* ]]; then
            echo "backend=true" >> $GITHUB_ENV
          else
            echo "backend=false" >> $GITHUB_ENV
          fi

      - id: set_output
        run: |
          echo "::set-output name=deploy_frontend::$(echo $frontend)"
          echo "::set-output name=deploy_backend::$(echo $backend)"

  build-frontend:
    runs-on: ubuntu-latest
    needs: check-pr-comments
    if: needs.check-pr-comments.outputs.deploy_frontend == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        working-directory: React/frontend

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./*
        working-directory: React/frontend/build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: React/frontend/build/release.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    if: needs.check-pr-comments.outputs.deploy_frontend == 'true'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact

      - name: List files after download
        run: ls -la

      - name: Create directory for artifact
        run: mkdir -p React/frontend/build

      - name: Move downloaded artifact to the correct directory
        run: mv frontend-artifact.zip React/frontend/build/release.zip || mv *.zip React/frontend/build/release.zip

      - name: Verify ZIP File Before Unzipping
        run: ls -la React/frontend/build

      - name: Unzip artifact for deployment
        run: unzip release.zip
        working-directory: React/frontend/build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8980AA3A4A1F460395B4C85A85942C18 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D72111B5ADDB4F3DAC9ADAC9E1E32553 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29CEAE5DB45E4433AE10AD8E5C077DA6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myvdtreact'
          slot-name: 'Production'
          package: React/frontend/build

  deploy-backend:
    runs-on: ubuntu-latest
    needs: check-pr-comments
    if: needs.check-pr-comments.outputs.deploy_backend == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          cd MyFlask
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-backend-app'  # Replace with your backend web app name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
