name: Build and deploy Node.js app to Azure Web App - reactUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up the Node.js version to use
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Go to the React app folder and install dependencies, then build the app
      - name: Install dependencies and build React app
        run: |
          cd ./React/frontend  # Change to the directory where your React app is
          npm install
          npm run build  # This will generate the 'build' folder with the production-ready app

      # Zip the build folder to prepare for deployment
      - name: Zip the build folder for deployment
        run: |
          cd ./React/frontend/build
          zip -r release.zip .  # Zip the contents of the 'build' directory

      # Upload the zip file as an artifact for the next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./React/frontend/build/release.zip  # Path to the zipped build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Download the artifact generated by the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip node-app/release.zip

      # Login to Azure using credentials stored in secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      # Deploy the unzipped build folder to the Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reactUI'  # Replace with your Azure Web App name
          slot-name: 'production'
          package: ./build  # Path to the unzipped build directory
