name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'  # Use the same Node.js version as your local environment

      # Install dependencies and build the React app
      - name: Install dependencies and build React app
        run: |
          cd React/frontend  # Ensure this points to your React app directory
          npm install
          npm run build  # Build the production-ready files

      # Debug step: List build folder contents after running npm run build
      - name: List build folder contents
        run: ls -la ./React/frontend/build  # List the contents of the build folder to verify it contains the necessary files

      # Zip the build folder for deployment
      - name: Zip the build folder
        run: |
          cd React/frontend
          zip -r build.zip build/

      # Debug step: List the files inside the zip archive
      - name: List contents of the zip archive
        run: unzip -l React/frontend/build.zip  # List the contents of the zip file to verify it contains the necessary files

      # Upload the build artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./React/frontend/build.zip  # Upload the zip file for deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for OIDC-based login

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Debug step: List files after downloading the artifact
      - name: List files after downloading the artifact
        run: ls -la

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip build.zip

      # Debug step: List files after unzipping
      - name: List files after unzipping
        run: ls -la ./build  # Check the files in the unzipped build directory before deploying

      # Login to Azure using credentials from GitHub Secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
       

      # Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myWebAppReact'  # Replace with your Azure Web App name
          package: ./build  # Path to the unzipped build directory
