name: Build and deploy Node.js and Python apps to Azure Web Apps

on:
  pull_request:
    branches:
      - main
    types: 
      - closed
  workflow_dispatch:

jobs:
  check-pr-comments:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'UAT'
    outputs:
      deploy_frontend: ${{ steps.set_output.outputs.deploy_frontend }}
      deploy_backend: ${{ steps.set_output.outputs.deploy_backend }}
    steps:
      - name: Extract PR body content
        id: extract_content
        run: echo "PR_BODY=$(echo '${{ github.event.pull_request.body }}')" >> $GITHUB_ENV

      - name: Determine deployment type
        id: set_output
        run: |
          PR_BODY="${{ env.PR_BODY }}"
          
          frontend=false
          backend=false
          
          if [[ "$PR_BODY" == *"frontend::"* ]]; then
            frontend=true
          fi
          
          if [[ "$PR_BODY" == *"backend::"* ]]; then
            backend=true
          fi
          
          echo "::set-output name=deploy_frontend::$frontend"
          echo "::set-output name=deploy_backend::$backend"

  build-frontend:
    runs-on: ubuntu-latest
    needs: check-pr-comments
    if: ${{ needs.check-pr-comments.outputs.deploy_frontend == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: React/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('React/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build --if-present
        working-directory: React/frontend

      - name: Check build output for static assets
        run: |
          echo "Listing files generated by npm build in the /static directory"
          ls -la React/frontend/build/static
          ls -la React/frontend/build/static/css
          ls -la React/frontend/build/static/js
          ls -la React/frontend/build/static/media

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./*
        working-directory: React/frontend/build

      - name: Verify ZIP File After Zipping
        run: unzip -l React/frontend/build/release.zip  # List contents of the ZIP to check static folder

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: React/frontend/build/release.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    if: ${{ needs.check-pr-comments.outputs.deploy_frontend == 'true' }}
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: ./artifact-dir  # Download the artifact to a known directory

      - name: List downloaded artifact files
        run: ls -la ./artifact-dir  # Verify artifact download

      - name: Unzip artifact for deployment
        run: unzip ./artifact-dir/release.zip -d ./unzipped

      - name: List files in unzipped directory (Check if static files are unzipped)
        run: ls -la ./unzipped/static  # Check if static folder exists

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myvdtreact'
          slot-name: 'Production'
          package: ./unzipped
          clean: true  # Ensures the directory is cleaned before deployment
