name: Build and deploy Node.js app to Azure Web App - myvdtreact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        working-directory: React/frontend

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./*
        working-directory: React/frontend/build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: React/frontend/build/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: React/frontend/build  # Specify the directory to download the artifact to

      - name: Create directory for artifact
        run: mkdir -p React/frontend/build

      - name: Move downloaded artifact to the correct directory
        run: mv node-app.zip React/frontend/build/release.zip  # Move the artifact to the correct directory

      - name: Verify ZIP File Before Unzipping
        run: ls -la React/frontend/build  # Check that the artifact is in the right place

      - name: Unzip artifact for deployment
        run: unzip release.zip
        working-directory: React/frontend/build  # Unzip in the build directory

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8980AA3A4A1F460395B4C85A85942C18 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D72111B5ADDB4F3DAC9ADAC9E1E32553 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29CEAE5DB45E4433AE10AD8E5C077DA6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myvdtreact'
          slot-name: 'Production'
          package: React/frontend/build  # Path to the unzipped files
