name: Build and deploy Node.js app to Azure Web App - myvdtreact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          cd React/frontend   # Navigate to the frontend directory
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          cd React/frontend/build  # Navigate to the build directory
          zip -r release.zip ./*   # Create a ZIP file of the build directory
        working-directory: React/frontend/build  # Set the working directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: React/frontend/build/release.zip   # Path to the zip file
      
      - name: List build directory
        run: ls -la React/frontend/build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
        working-directory: React/frontend/build  # Ensure you are in the correct directory
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8980AA3A4A1F460395B4C85A85942C18 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D72111B5ADDB4F3DAC9ADAC9E1E32553 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29CEAE5DB45E4433AE10AD8E5C077DA6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myvdtreact'
          slot-name: 'Production'
          package: React/frontend/build  # Path to the unzipped files
