name: Build and deploy Node.js app to Azure Web App - reactUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up the Node.js version to use
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Go to the React app folder, install dependencies, and build the app
      - name: Install dependencies and build React app
        run: |
          cd ./React/frontend  # Ensure this points to your React app directory
          npm install
          npm run build  # This will generate the 'build' folder with the production-ready app

      # Debug step: List the build folder contents to ensure it's created
      - name: List build folder contents
        run: |
          ls -la ./React/frontend/build  # Check if the build folder exists and contains files

      # Zip the build folder for deployment
      - name: Zip the build folder for deployment
        run: |
          cd ./React/frontend
          zip -r release.zip ./build  # Zip the entire build folder

      # Upload the zip file as an artifact for the next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./React/frontend/release.zip  # Upload release.zip for deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      # Download the artifact generated by the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Debug step: List the downloaded artifact to ensure the file exists
      - name: List files after downloading artifact
        run: ls -la

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Debug step: List files after unzipping to ensure the build folder is there
      - name: List files after unzipping
        run: ls -la ./build  # Check that the build folder was unzipped

      # Login to Azure using credentials stored in secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy the unzipped build folder to the Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reactUI'  # Replace with your Azure Web App name
          slot-name: 'production'
          package: ./build  # Ensure the build folder path is correct
